#!/bin/bash

rm results_*
rm *.cmi *.cmo
atdgen -t results.atd
atdgen -j results.atd
ocamlfind ocamlc -c -package atdgen,curl,str,netstring map2.mli map2.ml encoding.ml category.ml results_t.mli results_j.mli results_t.mli results_j.ml utils.ml
